dist: bionic

language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libprotobuf-dev libboost-dev protobuf-compiler
  - pecl install uopz
  - printf "\n" | pecl install mysql_xdevapi
  - echo "extension=uopz.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=mysql_xdevapi.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update

script:
  - composer install
  - php ./vendor/bin/phpunit -c ./phpunit.xml

after_script:
  - php ./vendor/bin/test-reporter --coverage-report=build/clover.xml

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
