dist: bionic

language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libprotobuf-dev libboost-dev protobuf-compiler
  - phpenv config-rm xdebug.ini
  - pecl channel-update pecl.php.net
  - pecl install uopz-6.1.2
  - git clone https://github.com/php/pecl-database-mysql_xdevapi.git ./mysql_xdevapi
  - cd ./mysql_xdevapi
  - git checkout 8.0.20
  - phpize
  - ./configure --enable-mysql-xdevapi --with-boost --with-protobuf
  - make -j"$(nproc)"
  - make install
  - make clean
  - cd ../
  - echo "extension=mysql_xdevapi.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update

script:
  - composer update
  - phpdbg -qrr ./vendor/bin/phpunit -v -c ./phpunit.xml

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php ./vendor/bin/test-reporter --coverage-report=build/clover.xml; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

matrix:
  include:
    - php: 7.3
    - php: 7.4
      env:
        - TEST_COVERAGE=true
        - CS_CHECK=true
