dist: bionic

language: php
sudo: enabled

services:
  - docker

script:
  - docker-compose up -d
  - composer install
  - docker exec -it expressive-xdevapi_php-cli_1 php ./vendor/bin/phpunit -c ./phpunit.xml
  - docker stop $(docker ps -a -q)

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/test-reporter --coverage-report=build/clover.xml ; fi

before_install:
  - sudo apt-get update
  - sudo pip install docker-compose
  - docker-compose --version
  - composer self-update

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
