dist: bionic

language: php

before_script:
  - composer install

script:
  - composer unit-test

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/test-reporter --coverage-report=build/clover.xml ; fi

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get install -y libprotobuf-dev libboost-dev protobuf-compiler libxml2-dev build-essential openssl php7.3-dev
  - pecl install mysql_xdevapi
  - pecl install uopz
  - composer self-update

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
