dist: bionic

language: php

before_install:
  - sudo apt-get update

before_script:
  - pecl install uopz
  - pecl install mysql_xdevapi
  - composer self-update

script:
  - composer install
  - php ./vendor/bin/phpunit -c ./phpunit.xml

after_script:
  - php ./vendor/bin/test-reporter --coverage-report=build/clover.xml

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
