dist: bionic

language: php
sudo: enabled

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo pip install docker-compose
  - docker-compose --version
  - composer self-update

script:
  - docker-compose -f ./docker-compose-unittest.yml up -d
  - docker exec -it expressive-xdevapi_php-cli_1 composer install
  - docker exec -it expressive-xdevapi_php-cli_1 php ./vendor/bin/phpunit -c ./phpunit.xml
  - docker stop $(docker ps -a -q)

after_script:
  - php ./vendor/bin/test-reporter --coverage-report=build/clover.xml

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
