version: '3'

services:
  php-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        uid: "${UID}"
        user: "${USER}"
    tty: true
    working_dir: /home/xdevapi
    volumes:
      - .:/home/xdevapi
