FROM php:7.3.9-cli

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        libprotobuf-dev \
        libboost-dev \
        openssl \
        protobuf-compiler \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
		libicu-dev \
		libzip-dev \
		libxml2-dev \
		git \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install -j$(nproc) bcmath gd exif intl zip

RUN docker-php-source extract \
    && cd /usr/src/php/ext \
    && git clone https://github.com/php/pecl-database-mysql_xdevapi.git ./mysql_xdevapi \
    && cd mysql_xdevapi \
    && git checkout 8.0.17 \
    && phpize \
    && ./configure \
    && make -j8 \
    && make install \
    && docker-php-source delete

RUN pecl install uopz \
    && docker-php-ext-enable uopz

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Override with custom opcache settings
COPY container-build/php/config/xdebug.ini $PHP_INI_DIR/conf.d/
COPY container-build/php/config/mysql_xdevapi.ini $PHP_INI_DIR/conf.d/

WORKDIR /home/expressive-xdevapi
